
import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisResult } from "../types.ts";

export async function fetchLyricsAndAnalyze(song: string, artist: string): Promise<AnalysisResult> {
  const model = 'gemini-3-flash-preview';
  
  // The API key is injected automatically by the platform into process.env.API_KEY.
  // We initialize the client inside the function to ensure we always use the 
  // most up-to-date environment state during the call.
  const apiKey = process.env.API_KEY;
  
  if (!apiKey) {
    throw new Error("The API key is currently unavailable in the environment. Please ensure the project is correctly configured.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  const prompt = `
    Analyze the song "${song}" by "${artist}". 
    Perform an analytical reconstruction of its poetic content and thematic structure.
    
    Tasks:
    1. Identify official title, artist, release year, primary mood, and main theme.
    2. Provide a clean textual representation of the song's narrative/lyrics.
    3. Generate a frequency list of the 50 most significant unique words. 
       - EXCLUDE common stopwords (the, a, is, of, and, etc).
       - Focus on the thematic heart of the song.
    
    Return EXACTLY this JSON structure:
    {
      "metadata": {
        "title": "...",
        "artist": "...",
        "lyrics": "...",
        "mood": "...",
        "theme": "...",
        "year": "..."
      },
      "wordFrequencies": [
        { "text": "word", "size": number }
      ]
    }
  `;

  try {
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            metadata: {
              type: Type.OBJECT,
              properties: {
                title: { type: Type.STRING },
                artist: { type: Type.STRING },
                lyrics: { type: Type.STRING },
                mood: { type: Type.STRING },
                theme: { type: Type.STRING },
                year: { type: Type.STRING }
              },
              required: ["title", "artist", "lyrics", "mood", "theme", "year"]
            },
            wordFrequencies: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  text: { type: Type.STRING },
                  size: { type: Type.NUMBER }
                },
                required: ["text", "size"]
              }
            }
          },
          required: ["metadata", "wordFrequencies"]
        }
      }
    });

    if (!response.text) {
      throw new Error("No response generated by the model.");
    }

    return JSON.parse(response.text) as AnalysisResult;
  } catch (error) {
    console.error("Gemini Service Error:", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    
    // Guide the user if the error is related to project quota or key permissions
    if (message.includes("429") || message.includes("quota")) {
      throw new Error("Analysis limit reached. Please try again in a moment.");
    }
    
    throw new Error(`Analysis failed: ${message}. Ensure the song and artist details are correct.`);
  }
}
